### ISSUE TITLE
Change wallet amount response 

### ISSUE THREAD

**Issue by JeremyPansier** [my-cloud/ruthenium#146]
**Context**
The wallet amount response is an object holding one field, the amount.

**Description**
The wallet amount response should be a marshaled float.

**Tasks**
* [x] In `index.html`:
  ```
            function refresh_amount() {
                let data = {'address': $('#sender_address').val()}
                $.ajax({
                    url: '/wallet/amount',
                    type: 'GET',
                    data: data,
                    success: function (response) {
                        $('#wallet_amount').text(response);
                    },
                    error: function (error) {
                        console.error(error)
                    }
                })
            }
  ```
* [x] In `controller.go`:
  ```
		marshaledAmount, err := json.Marshal(float64(amountResponse.Amount) / network.ParticlesCount)
  ```
* [x] Delete `amount_response.go`
* [x] Update the API doc
