### ISSUE TITLE
Simplify transaction request

### ISSUE THREAD

**Issue by JeremyPansier** [my-cloud/ruthenium#153]
**Context**
The `PublicKey` field of the `server.TransactionRequest` struct is unused.

**Description**
Remove this field.

**Tasks**
Try to split the feature into small tasks.
* [x] Remove the `PublicKey` field of the `server.TransactionRequest` struct
* [x] Update the `index.html`
* [x] Update the API doc
