### ISSUE TITLE
Integrate Merkle tree

### ISSUE THREAD

**Issue by JeremyPansier** [my-cloud/ruthenium#206]
**Context**
1. Downloading the full blockchain will take more and more time with the blockchain growth.
1. Calculating the wallet amount for an address will take more and more time with the blockchain growth.

**Tasks**
* [ ] Integrate Merkle tree
* [ ] Make it possible to start validating and verifying blocks without the complete blockchain
* [ ] Make it possible to calculate the wallet amount for an address without the complete blockchain
