### ISSUE TITLE
Improve wallet amount calculation speed

### ISSUE THREAD

**Issue by JeremyPansier** [my-cloud/ruthenium#208]
**Context**
Calculating the wallet amount for an address will take more and more time with the blockchain growth.

**Description**
A transaction might store the sender wallet amount.

**Tasks**
* [ ] Make it possible to calculate the wallet amount for an address without the complete blockchain

**Comment by JeremyPansier** [comment]
**Suggestion**

* [ ] Add a field `SenderWalletAmount` to the transaction.
* [ ] Verify the value of this field when adding a new transaction and when verifying new blocks.
* [ ] For each transaction in a new block, store in map the sender address and the block index.
* [ ] Start amount calculation from this block index.

**Comment by JeremyPansier** [comment]
**Remark**

The CalculateTotalAmount need some fixes:
* [ ] The registered address must be uptodate when starting the calculation, so we need to use Block instead of BlockResponse
* [ ] The total amount must be positive only for each block, not for each transaction

**Comment by JeremyPansier** [comment]
**Suggestion**

* When there is consensus, store in a map the address with its balance and the block index.
* Start amount calculation from this block index.

**Comment by JeremyPansier** [comment]
**Suggestion**
* Store a map of utxo by address. Among the utxo is the income, which can be negative.
* The income utxo is updated each minute
* Verify that the transaction inputs don't exceed the wallet balance

**Comment by JeremyPansier** [comment]
**Suggestion**
* Store a map of UTXOs by address.
* Store a map of wallet balance by address
* Each transaction contains inputs and outputs. One or several inputs can be the income for an address, if positive, and shall be equal to this address wallet balance deduced from the other UTXOs for this address. The outputs sum cannot exceed the sum of the wallet balances of the inputs addresses, deduced the transaction fees.

**Comment by JeremyPansier** [comment]
**Suggestion**
* Store a map of UTXOs by address.
* Each transaction contains inputs and outputs.
* Find a new math operation for the income avoiding to calculate it each minute.
* To be added as a registered address in a block, a user must send a transaction of its total wallet balance to himself, and be registered in POH.
* If a registered address is removed, an unsigned transaction with no fee, with no input, and the total wallet balance to this address as a single output shall be included in the block by the node.

**Comment by JeremyPansier** [comment]
**Suggestion**
* Store a map of UTXO hash.
* The UTXO hash starts with 0 or 1 depending on if the sender deserves an income, then the block height, then the "h" letter followed by the transaction hash.
* Each transaction contains inputs and outputs.
* Each transaction contains a field UpateIncome.
* Find a new math operation for the income avoiding to calculate it each minute.
* To upate the income, the field UpateIncome must be set to true and the output address must be registered in POH, this might cost an additional fee.
* If a registered address is removed, an unsigned transaction with no fee, with all UTXOs of this address as inputs shall be included in the block by the node.
