### ISSUE TITLE
Integrate POH smart contracts

### ISSUE THREAD

**Issue by JeremyPansier** [my-cloud/ruthenium#213]
**Context**
Ruthenium blockchain currently use a smartcontract from another blockchain, Ethereum. To make the Ruthenium blockchain autosufficient, it needs to hold its own POH smartcontract.

**Description**
Integrate and use a POH smartcontract in Ruthenium.

**Tasks**
* [ ] Make Ruthenium support smartcontracts
* [ ] Handle private key generation
* [ ] Store POH smartcontract in the first block
