### ISSUE TITLE
Add universal basic income 

### ISSUE THREAD

**Issue by JeremyPansier** [my-cloud/ruthenium#75]
**Context**
Since the wallet amount is decreasing, people need a basic income to be interested in creating an account.  
Since the validators need an incentive to add as much as transactions as possible into the next block, the reward must depend on transaction fees.

**Description**
The validator reward must be replaced by the transaction fees.  
Every wallet must get a basic income.

**Tasks**
* [x] Verify the Proof of Humanity for every wallet
* [x] Give a basic income to every wallet that is registered
* [x] Replace the actual reward calculation by the transaction fees
